apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prices-predict-web
  namespace: prices-predict
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prices-predict-web
                port:
                  name: gunicorn