apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prediction-app-ingress
  namespace: prices-predict
spec:
  rules:
    - host: "a05120757a21d43b294e41387f3daaaf-0e229d2cc0311845.elb.us-west-2.amazonaws.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prediction-app-web
                port:
                  name: gunicorn