apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prediction-app-ingress
  labels:
    app: prediction-app-ingress
  namespace: prices-predict
spec:
  rules:
    - host: "aeb614c296e5e41fe8cc081e3489499f-28c3520f7c6a7937.elb.us-west-2.amazonaws.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prediction-app-web
                port:
                  name: gunicorn