apiVersion: batch/v1
kind: Job
metadata:
  name: prediction-app-job
  namespace: prices-predict
spec:
  template:
    metadata:
      labels:
        app: prediction-app
        role: prediction-app-job
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      restartPolicy: OnFailure
      containers:
        - name: prediction-app-job
          image: ovimihai/cdond-ml-microservice
          command:
            - /opt/venv/bin/python
          args:
            - app.py
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m