apiVersion: v1
kind: Service
metadata:
  name: prediction-app-web
  namespace: prices-predict
spec:
  selector:
    app: prediction-app
    role: web
  ports:
    - name: http
      port: 80
      targetPort: gunicorn