version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.0
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
        auth:
          username: ovimihai
          password: $DOCKERHUB_TOKEN

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}

      # run lint!
      - run:
          name: Run lint
          command: |
            . venv/bin/activate
            make lint
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make test

      - setup_remote_docker

      - run:
          name: Build image
          command: |
            . venv/bin/activate
            make docker-build

      - run:
          name: Push image
          command: |
            . venv/bin/activate
            make docker-push

      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA

      - run:
          name: Deploy
          command: |
            cd .circleci/k8s
            bash setup.sh
